### ISSUE TITLE
New sites to add

### ISSUE THREAD

**Issue by zaisty** [sethcottle/littlelink#103]
Hi,
Thanks for littlelink soft. It's really good.
I have request to add this sites to littlelink:
- ListenBrainz
- Discogs
- Mixcloud
- Filmweb (Polish movies database)
- GOG.com

I hope You to add those sites in future releases.
Good luck.

**Comment by Bashamega** [comment]
Hello:)
I would like to work on this

**Comment by sethcottle** [comment]
Discogs was just added in! I would consider adding the rest of these sites, ListenBrainz, Mixcloud, Filmweb, and GOG to LittleLink Extended. https://github.com/sethcottle/littlelink-extended

**Comment by sethcottle** [comment]
Hi, just so I can close this issue out, I added all of these services (except Discogs, since it's in the core LittleLink repo now) to [LittleLink Extended](https://github.com/sethcottle/littlelink-extended) in it's latest commit, [9a6ebbf](https://github.com/sethcottle/littlelink-extended/commit/9a6ebbf1fd555d5d924944dc2456e53ad1d470aa.), while I was updating the repository to align with this core repo. 😊
