### ISSUE TITLE
"Fanboy’s Annoyance" blocklist blocks .button-twitter

### ISSUE THREAD

**Issue by thrdroom** [sethcottle/littlelink#32]
Ublock Origin has a filterlist called "Fanboy’s Annoyance".
This list blocks elements with the class "button-twitter".

Other buttons from littlelink wont get blocked by this filterlist.
I dont know if you want to consider renaming that class, i just wanted to mention it here fyi.

**Comment by sethcottle** [comment]
Thanks for this callout, I just reviewed the Fanboy Annoyances List a bit more in-depth. It does look like it could impact `button-facebook` and `button-twitter`. If someone also has Fanboy-Social List enabled it looks like it could impact `button-tumblr`, `button-twitter`, `button-youtube`, `button-linkedin`, and `button-facebook` as well.

We'll have to decide if renaming some of these classes is the best route, or letting these lists do their job and if a user is looking to have these blocked, they'll be blocked.

**Comment by Xenthys** [comment]
Hey there, these lists' job is usually to block the aforementioned buttons because they tend to embed content from external hosts, therefore tracking which websites you're browsing. The Facebook "like" button is a good example.

If my opinion is of interest, I don't want these social networks to follow me everywhere but I'm still interested to know the person can be reached there, after all I'm curious enough to be visiting their website and may want to get in touch or simply follow them on Twitter for further content. In this specific case, I do not consider these buttons as annoyances since they are precisely what I'm looking for when I visit a LittleLink (or equivalent) page.

I would definitely say to keep them as-is if the logos were remotely hosted, but it's not the case here. 👍

**Comment by sethcottle** [comment]
Resolved by updating quite a few of the naming schemas and checked the updated names against the "Fanboy’s Annoyance" list. Thanks again! Here's the commit!

https://github.com/sethcottle/littlelink/commit/b9b5a86496507538845103dae924a9bdd601a84b
