### ISSUE TITLE
Multi-user

### ISSUE THREAD

**Issue by finkiki** [sethcottle/littlelink#39]
Hello,

Is it possible to manage several users at once with littlelink ? 

I'd like to create by myself a littlelink page for at least 30-40 people. Is this doable in an easy way ?

On the website, I'd like several people to have their  littlelink page.

Exemple.com/user1
Exemple.com/user2
...

**Comment by sethcottle** [comment]
Very doable, but quite manual! You just need to copy the `index.html` page, rename it, and edit the contents. For example, if I wanted my personal LittleLink page to appear at `example.com/seth` I would rename the page `seth.html` and then I can navigate to example.com/seth to visit that page. 

Depending on how your hosting is set up, you may have to navigate to example.com/seth.html to actually get to the page since by default most hosting services do not include clean URLs but can be easily enabled. If you're using a service like Vercel for hosting, you can include a `vercel.json` file that includes:

```
{
  "cleanUrls": true
}
```

This will allow you to navigate to  `example.com/seth` instead of  `example.com/seth.html`. See the documentation from Vercel here: [https://vercel.com/docs/cli#project-configuration/clean-urls](https://vercel.com/docs/cli#project-configuration/clean-urls)
