### ISSUE TITLE
Mastodon verification not working

### ISSUE THREAD

**Issue by corite** [sethcottle/littlelink#73]
The mastodon verification does not seem to be working (At least not for my mastodon.social profile). 
Although the `rel=me` attribute is already present in the `index.html` body, the verified symbol only showed up after I added another link to my profile from the page header.
I am not sure though if the problem is that the link is not in the header or that there are multiple `rel` attributes on the link.

Do you know what the source of this Problem is? Have you tested the currently active version?

**Comment by sethcottle** [comment]
I'll dig into this today and give it a try! From the documentation I read through Mastodon, it didn't mention this having to be present in `<head>` . I'll let you know what I find in a few hours!

**Comment by sethcottle** [comment]
Okay, just gave this a whirl with a mastodon.social profile I set up. I used the [littlelink.io](https://littlelink.io) homepage as my test link. Looks like code wise, totally works. I added the link to Mastodon before it pushed to the live site. Then I did several refreshes and hard refreshes to attempt to get the link to verify, but that didn't seem to do the trick. After trying that a few times I went to "Edit profile" and hit Save Changes and I'm assuming that forced mastodon.social to recheck for the `rel="me"` because it instantly verified as soon as I did that. 

So, I would assume it was just a check delay that made it seem like it wasn't working. They likely aren't checking that often for the `rel="me"` to perform the verification, they might only check at time of Save, I'm not quite sure. Regardless, it isn't an issue with how the link is presented in LittleLink. It's able to be verified with the current configuration. 

https://i.gyazo.com/2d4b728aa940343913b07e14567cf563.mp4
