### ISSUE TITLE
how can i add email on little link

### ISSUE THREAD

**Issue by krafi-org** [sethcottle/littlelink#86]
https://ibb.co/5jckQXN
actually to add anything on little link it alaways ask for URL that mean i have to add HTTPS://
but how can i add https on email ? 

another thing , i couldnt find any easy solution to install it as my localhost , i am using docker , i dont know docker stuff too much. any easy doc ? 
thanks for reading my bad English

**Comment by sethcottle** [comment]
I assume you're using a fork of LittleLink? I can't tell exactly which fork it is from the prompt in that screenshot alone.

Closing for now, since that is unsupported in this repo of LittleLink. For this repo, all you do is update the 'hyperlink' with a 'mailto:'. I'd suggest opening an issue in your forks repository!
