### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by toddlyons** [sethcottle/littlelink#87]
I logged in today and saw "An update is available". I ran the updater from within the app. It backed up, applied it, and claimed to have updated successfully. When I was returned to the admin screen it still reported "An update is available". I logged in from a private window: "An update is available". 

So, I ran the updater again and it bricked. White screen.

I restored from backup and had the same result, but only ran the updater once. Is the issue with the version detection?

**Comment by sethcottle** [comment]
Hi @toddlyons, LittleLink doesn't have an updater or update functionality beyond pulling in the latest 'main' branch changes, so I assume you're using a fork of LittleLink! I'm going to go ahead and close this issue since it's unrelated to the OG repo, you'll want to open an issue with whatever community fork you're leveraging!
